<?php

namespace App\Models\Bank;

use App\Classes\TochkaBank\BankAPI;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Crypt;

class Card extends Model
{
    use HasFactory;

    protected $dates = ['expiredAt'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function geo()
    {
        return $this->belongsTo(Geo::class);
    }

    public function seller()
    {
        return $this->belongsTo(Seller::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class, 'card_id');
    }

    public function getAccountIdAttribute()
    {
        return $this->account_code .'/'. $this->bank_code;
    }

    public function getUserAttribute()
    {
        return $this->user()->first();
    }

    public function updateNumberAttribute(string $value = null): void
    {
        $value = $value ? $value : $this->number;
        $number = self::getNumberSplit($value);
        if($number[1] === '****' and $number[2] === '****')
        {
            $value = isset($this->attributes['number']) ? Crypt::decryptString($this->attributes['number']) : $this->attributes['number'];
            $number = self::getNumberSplit($value);
        }

        $this->attributes['head'] = $number[0];
        $this->attributes['tail'] = $number[3];
    }

    public function setNumberAttribute(string $value): void
    {
        $this->updateNumberAttribute($value);
    }

    private static function getNumberSplit($number): array
    {
        $number = str_replace(' ', '', $number);
        return str_split($number, 4);
    }


    public static function getCollectApi(): \Illuminate\Support\Collection
    {
        $cardsApi = BankAPI::make()->getCards();

        if(!isset($cardsApi->Data)) {
            dd($cardsApi);
        }
        $cards =[];
        foreach ($cardsApi->Data->cards as $card) {
            $matches = self::getNumberSplit($card->maskedPan);

            $cards[] = collect([
                'account_code' => $card->accountCode,
                'bank_code' => $card->bankCode,
                'number' => $card->maskedPan,
                'head' => $matches[0],
                'tail' => $matches[3],
                'card_description' => $card->cardDescription,
                'card_type' => $card->cardProductType,
                'expiredAt' => Carbon::createFromFormat('m#y H', $card->expirationDate. ' 00'),
                'state' => true ? $card->previewState == 'Active' : false
            ]);
        }

        return collect($cards);
    }

    public static function refreshApi()
    {
        $cards = self::getCollectApi();

        self::upsert(
            $cards->toArray(),
            [
                'number',
                'card_description',
                'head',
                'tail',
                'card_type',
                'expiredAt',
                'state'
            ]
        );
    }

    public function getStateAttribute()
    {
        return $this->attributes['state'] ? 'Активная' : 'Закрытая';
    }

    public static function all($columns = ['*'])
    {
        return parent::all($columns); // TODO: Change the autogenerated stub
    }

    public function getPayments()
    {
        return $this->payments()->where('amount', '>', 0);

    }

    public function amount()
    {
        return $this->payments()
            ->sum('amount');
    }
}
